version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - ZAP_HOST=127.0.0.1
      - ZAP_PORT=8081
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
