app = "zap-security-scanner"
primary_region = "ord"

[build]

[env]
  PORT = "5000"
  ZAP_HOST = "127.0.0.1"
  ZAP_PORT = "8081"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
